### ISSUE TITLE
mistake in an example

### ISSUE THREAD

**Issue by Claudio-Chies** [franzbu-png/control-systems-2#1]
https://github.com/franzbu-png/control-systems-2/blob/bc01f3f5158a5b51f56e42347e67cab0ec541d6b/04_diverse_SISO/04_alg_stab_bsp.tex#L51

there are some errors in this  line.
it should be: 
                0  &1946k_p& 731 & 255-42k_p\\

Cheers

**Comment by franzbu-png** [comment]
You're right, thanks a lot for sharing!
